version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: minerva
      POSTGRES_USER: minerva
      POSTGRES_PASSWORD: minerva_dev
      # Optimized for laptop development
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minerva -d minerva"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - minerva

  minerva:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://minerva:minerva_dev@postgres:5432/minerva
      CONFIG_PATH: /app/config/development.yaml
      LOG_LEVEL: INFO
      PYTHONPATH: /app
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - minerva
    profiles:
      - full

  # Redis for caching (optional, for production)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - minerva
    profiles:
      - full

volumes:
  postgres_data:
  redis_data:

networks:
  minerva:
    driver: bridge