# Test configuration with disabled models for Phase 2 testing
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false
  log_level: "INFO"
  cors_origins:
    - "http://localhost:3000"

database:
  url: "postgresql+asyncpg://metamcp:metamcp_dev@localhost:5432/metamcp"
  pool_size: 10
  max_overflow: 20
  echo: false

# Selection modes
selection_modes:
  fast:
    bm25_candidates: 24
    dense_candidates: 16
    rerank_candidates: 16
    expose_tools: 5
    enable_planner: false
    timeout_ms: 200
    
  balanced:
    bm25_candidates: 48
    dense_candidates: 32
    rerank_candidates: 32
    expose_tools: 8
    enable_planner: false
    timeout_ms: 500

# Disabled model configuration for testing
models:
  embeddings:
    provider: "off"  # Disable for testing
    dimensions: 384
    batch_size: 32
    device: "cpu"
    
  reranker:
    provider: "off"  # Disable for testing
    batch_size: 16
    device: "cpu"
    
  planner:
    provider: "off"  # Already disabled by default
    max_retries: 2
    timeout_seconds: 30

# Search configuration
search:
  bm25_weight: 0.7
  dense_weight: 0.3
  mmr_lambda: 0.3
  utility_scoring:
    relevance_weight: 0.5
    success_weight: 0.2
    latency_penalty: 0.2
    risk_penalty: 0.1
  cache_ttl_seconds: 300
  cache_size_mb: 64

# Storage
storage:
  data_dir: "./data"
  bm25_index_dir: "./data/bm25"
  snapshots_dir: "./data/snapshots" 
  logs_dir: "./logs"

# Security
security:
  admin_username: "admin"
  admin_password: "admin123"
  secret_key: "test-secret-key"
  secrets:
    provider: "file_vault"
    vault_path: "./data/secrets.vault"
    
# Ingestion
ingestion:
  refresh_interval_hours: 24
  concurrent_origins: 5
  request_timeout_seconds: 30
  retry_attempts: 3
  retry_backoff_seconds: 2
  enable_probes: true
  probe_timeout_seconds: 10
  max_probe_concurrency: 3

# Observability
observability:
  enable_tracing: true
  enable_metrics: true
  otel:
    service_name: "meta-mcp-test"
    service_version: "0.1.0"
  metrics:
    endpoint: "/metrics"
    buckets: [0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0]

# Circuit breakers
circuit_breakers:
  default:
    failure_threshold: 5
    timeout_seconds: 60
    expected_recovery_seconds: 30